### PR TITLE
getMeasure

### PR DESCRIPTION
**Pull request by trangdang168**
This pull request includes:
- A bug fix for PartSeries (missing series' names)
- Removal of unnecessary files
- New `getMeasure` method based on `getBeatStrength`

### CODE REVIEW

**Review by alexandermorgan — CHANGES_REQUESTED** [review]
This is close to what we need, but not quite right. We want the numbers of measures at the offset where they start in each voice. Your code gives the measure number of each note or rest event. The tricky thing here is finding the measure objects. They're not in the _getPartSeries df, or in the _getFlatParts thing. I found three ways to get measure objects, and two of them seem reasonable. Which of these two do you think is best?
1)
parts = list(self.score.getElementsByClass(stream.Part))
partMeasures = [pd.Series({m.offset: m.measureNumber}) for part in parts for m in part.makeMeasures()]
df = pd.concat(partMeasures, axis=1)

2)
If you use part.semiFlat instead of part.flat, semiFlat still has the measure objects in it. Then you can getElementsByClass(['Measure']) and then use their .measureNumber and .offset values to build the series and dataframe. If you go this route, you could maybe just change ._getFlatParts to ._getSemiFlatParts so that we don't have both flat and semiflat.


Also, whichever way you use, remember to use na_action='ignore' in your applymap call.

**Comment by trangdang168** [comment]
Thanks for the feedback! I was trying to mimic the Gould system that accesses both a note's beat strength and measure, but that's a rather close-minded approach. I would go with the second one, because `self.score.getElementsByClass(stream.Part)` should be called only once.

**Comment by alexandermorgan** [comment]
> Thanks for the feedback! I was trying to mimic the Gould system that accesses both a note's beat strength and measure, but that's a rather close-minded approach. I would go with the second one, because `self.score.getElementsByClass(stream.Part)` should be called only once.

Ok, the second one it is. Just ping me when you have it updated.

**Comment by trangdang168** [comment]
Moving this getMeasure issue to branch `trang-dev`

**Pull request closed without merging**
